/**
 * Stamp the build with the commit it came from.
 *
 * Two copies of the same fact, for two different questions:
 *
 *   src/version.ts      baked into the bundle — "which commit is the page I
 *                       am looking at?"
 *   public/version.json served beside the bundle — "which commit is the
 *                       newest one published?" A page that was open before a
 *                       deploy still carries the old bundle, fetches this,
 *                       sees a different commit, and says so.
 *
 * Netlify sets COMMIT_REF; anywhere else the checkout answers. Both files
 * are generated, never committed — otherwise every build dirties the tree.
 */
import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const client = resolve(here, '..');

function git(args) {
   try { return execSync(`git ${args}`, { cwd: client, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); }
   catch { return ''; }
}

const sha = process.env.COMMIT_REF || process.env.GITHUB_SHA || git('rev-parse HEAD') || 'unknown';
const committedAt = git(`show -s --format=%cI ${sha}`) || '';
const message = git(`show -s --format=%s ${sha}`) || '';
const builtAt = new Date().toISOString();

const info = { sha, short: sha.slice(0, 7), committedAt, message, builtAt };

mkdirSync(resolve(client, 'public'), { recursive: true });
writeFileSync(resolve(client, 'public/version.json'), JSON.stringify(info, null, 2) + '\n');
writeFileSync(
   resolve(client, 'src/version.ts'),
   `// Generated by scripts/version.mjs at build time. Do not edit or commit.\n`
   // Typed as plain strings, not literals: the footer compares the sha with
   // 'unknown' and with other builds, and tsc -b rejects comparing a literal
   // type with a value it can never equal.
   + `export const BUILD: { sha: string; short: string; committedAt: string; message: string; builtAt: string } = ${JSON.stringify(info, null, 2)}\n`,
);

console.log(`[version] ${info.short} · ${message || '(no message)'} · built ${builtAt}`);
